name: Pipeline com Erro Real de Configuração

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Preparação
        run: echo "Iniciando verificação do arquivo de configuração..."

      - name: Verificar arquivo de configuração
        id: check_config
        run: |
          TIMESTAMP="$(date --iso-8601=seconds)"
          LOGFILE=logs/config_error.log
          JSONFILE=logs/config_error.json

          mkdir -p logs

          CONFIG_FILE="config.yml"

          # Tenta ler o arquivo de configuração
          if [ ! -f "$CONFIG_FILE" ]; then
            echo "ERRO CRÍTICO: Arquivo de configuração '$CONFIG_FILE' não encontrado." >&2

            # JSON estruturado para IA
            cat > "$JSONFILE" <<EOF
{
  "timestamp": "$TIMESTAMP",
  "error_type": "missing_file",
  "file": "$CONFIG_FILE",
  "exit_code": 1,
  "message": "Arquivo de configuração obrigatório ausente.",
  "suggestion": "Adicionar '$CONFIG_FILE' no repositório ou no caminho correto antes de rodar a pipeline."
}
EOF

            echo "[$TIMESTAMP] CRITICAL: $CONFIG_FILE missing" > "$LOGFILE"
            exit 1
          fi

          echo "Arquivo de configuração encontrado, continuando..."

      - name: Step não alcançada
        run: echo "Este step não será executado se o config.yml estiver ausente."
