name: Simulação de Pipeline

on:
  workflow_dispatch:  # Permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Exemplo simples
        run: echo "🚀 Pipeline rodando com sucesso no GitHub Actions!"
