name: Simulação de Erro de Sintaxe YAML

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Step OK
        run: echo "Início da execução."
        
      - name: Step com Erro de Sintaxe
        run: echo "Tentando executar comando..."
        # Linha propositalmente mal indentada (muito para a esquerda)
        - name: Este Step NÃO Deveria Ter Nome
          run: echo "Este bloco está mal formado e vai falhar o parser."
