name: Simulação de Pipeline com Log

on:
  workflow_dispatch: # Permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: 1. Step de Preparação
        run: echo "Iniciando verificação de dependências..."
        
      - name: 2. Step que Falha e Gera Log
        # | representa um bloco de comando multi-linha
        run: | 
          # 1. Mensagem de erro que será vista no log do GitHub
          echo "ERRO CRÍTICO: Falha na validação de formato. O arquivo de configuração está ausente." >&2
          
          # 2. Comando que força a falha (exit 1)
          exit 1 

      - name: 3. Step que Não Roda
        run: echo "Este step não será alcançado."
