name: Simulação de Pipeline

on:
  workflow_dispatch:  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Forçando um Erro Proposital
        # ESTA LINHA VAI FALHAR A EXECUÇÃO DO JOB
        run: exit 1
